# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e64af0c6d111afff15bd0c187ec68083d3c0427f673303de94da4a68cbd942284234d53c01fe065799b82e4af320d1f36f7be2bcd3fcd4af30831fd7f9570fb

test:
  secret_key_base: 0949c737f88705b1d58394f161cc47979ad81d06bc00b9a4cbd6c93691fabdd7c854f5cdaa1bf3cbb48be3ec5a5c1b1892dd16d0bd430b407d0bd6e6593d4817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
